{% set name = "wavespectra" %}
{% set version = "3.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b527e2aa6b0f500db34aa10a55efe489561fe99c66256be023467c54410377d3


build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('fortran') }}
  host:
    - python >=3.8,<3.12
    - pip
    - numpy
    - pytest-runner
  run:
    - python >=3.8,<3.12
    - click
    - cmocean
    - dask
    - gcsfs
    - fsspec
    - matplotlib-base
    - numpy
    - pandas
    - python-dateutil
    - pyyaml
    - sortedcontainers
    - scipy
    - typing_extensions
    - toolz
    - xarray
    - numba
    - zarr
    - attrdict
    - decorator
    - importlib-metadata

test:
  imports:
    - wavespectra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wavespectra/wavespectra
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python library for ocean wave spectra
  description: |
    Wavespectra is an open source project for working with ocean wave spectral data. 
    The library is built on top of xarray, leveraging from xarray’s labelled 
    multi-dimensional arrays and making dealing with wave spectra simple and fast..
  doc_url: https://wavespectra.readthedocs.io/en/latest/
  dev_url: https://github.com/wavespectra/wavespectra

extra:
  recipe-maintainers:
    - RubendeBruin
    - rafa-guedes
