{% set name = "wavespectra" %}
{% set version = "3.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0066328ee8272565ba35ee5b7569ea8ca3e4f8fb1c61f011d7da062e3c10a53


build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
    - pytest-runner
  run:
    - python
    - click
    - dask
    - gcsfs
    - fsspec
    - h5netcdf
    - matplotlib-base
    - numpy
    - netCDF4
    - pandas
    - python-dateutil
    - pyyaml
    - sortedcontainers
    - scipy
    - xarray
    - zarr
    - attrdict
    - importlib-metadata

test:
  imports:
    - wavespectra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wavespectra/wavespectra
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python library for ocean wave spectra
  description: |
    Wavespectra is an open source project for working with ocean wave spectral data. 
    The library is built on top of xarray, leveraging from xarray’s labelled 
    multi-dimensional arrays and making dealing with wave spectra simple and fast..
  doc_url: https://wavespectra.readthedocs.io/en/latest/
  dev_url: https://github.com/wavespectra/wavespectra

extra:
  recipe-maintainers:
    - RubendeBruin
    - rafa-guedes
